# Generated by Django 4.1.7 on 2023-03-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
